package com.norypt.haven.ui.navigation

/** Navigation routes. Arguments are opaque ids only — never content. */
object Routes {
    const val WELCOME = "welcome"
    const val SETUP = "setup"
    const val UNLOCK = "unlock"
    const val FORGOT_PASSWORD = "unlock/forgot"
    const val TODAY = "today"
    const val REMINDERS = "reminders"
    const val REMINDER_EDIT = "reminder/edit?id={id}&taskId={taskId}"
    fun reminderEdit(id: String? = null, taskId: String? = null) = "reminder/edit?id=${id ?: ""}&taskId=${taskId ?: ""}"
    const val REMINDER_DETAIL = "reminder/{id}"
    fun reminderDetail(id: String) = "reminder/$id"
    const val TASKS = "tasks"
    const val TASK_LIST = "tasks/list/{listId}"
    fun taskList(listId: String) = "tasks/list/$listId"
    const val TASK_DETAIL = "task/{id}"
    fun taskDetail(id: String) = "task/$id"
    const val TASK_EDIT = "task/edit?id={id}&listId={listId}"
    fun taskEdit(id: String? = null, listId: String? = null) = "task/edit?id=${id ?: ""}&listId=${listId ?: ""}"
    const val PASSWORDS = "passwords"
    const val PASSWORD_UNLOCK = "passwords/unlock"
    const val PASSWORD_DETAIL = "passwords/{id}"
    fun passwordDetail(id: String) = "passwords/$id"
    const val PASSWORD_EDIT = "passwords/edit?id={id}"
    fun passwordEdit(id: String? = null) = "passwords/edit?id=${id ?: ""}"
    const val PASSWORD_GENERATOR = "passwords/generator"
    const val BACKUP = "backup"
    const val ALARM_READINESS = "alarms/readiness"
    const val RINGING = "ringing"
    const val MISSED = "missed"
    const val SETTINGS = "settings"
    const val SETTINGS_SECURITY = "settings/security"
    const val SETTINGS_APPEARANCE = "settings/appearance"
    const val ABOUT = "about"
}
